apiVersion: v1
kind: Secret
metadata:
  name: credentials-infinispan
type: Opaque
stringData:
  username: admin123
  password: 'admin123'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: app
  labels:
    app: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: infinispan
          image: infinispan/server:14.0.5.Final
          ports:
            - containerPort: 11222
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: credentials-infinispan
                  key: username
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: credentials-infinispan
                  key: password
